# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Server

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x,17.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache pnpm modules
      uses: actions/cache@v2
      env:
        cache-name: cache-pnpm-modules
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-
    - uses: pnpm/action-setup@v2.2.1
      with:
        version: latest
        run_install: true
    - name: Build Server
      run: |
        pnpm build
    - name: Setup MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        # MYSQL_ROOT_PASSWORD - root superuser password
        mysql root password: gasdoldedseasder
        # MYSQL_DATABASE - name for the default database that is created
        mysql database: gserver
        # MYSQL_USER - create the specified user with superuser power for created database
        mysql user: gserver
        # MYSQL_PASSWORD - specified superuser password which user is power for created database
        mysql password: gserver
    - name: Deploy to Vercel
      run: | 
        if [ ! -n "$(git remote -v | grep wibus-wee)" ]; then
        echo "组织仓库不能继续操作"
        else
        npx vercel --token ${VERCEL_TOKEN} --prod
        fi
      env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          NODE_ENV: production
          CORS_SERVER: gs-admin.vercel.app,g.iucky.cn
