name: Pull Request Auto Approve CI

on:
  issue_comment:
    types: [created]

jobs:
  pull-request-auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request Auto Approve
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.BOT_REVIEW_TOKEN }}
          script: |
            const pullRequest = context.payload.issue.pull_request;
            const commentUser = context.payload.comment.user.login;
            const commentBody = context.payload.comment.body;
            const repoOwner = context.payload.repository.owner.login;
            if ( commentBody.includes('/approve') ){
              if (commentUser === repoOwner) {
                github.rest.pulls.createReview({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: pullRequest.number,
                  event: 'APPROVE'
                });
              } else {
                github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: pullRequest.number,
                  body: `
                  ## ⚠️ Permission denied

                  Only the **owner** of the project can approve the pull request.

                  只有**项目的所有者**才能发送如 `/approve` 的命令自动批准拉取请求。若你继续发送此命令，你将会被社区禁言。
                  `
                });
              }
            }
            
