name: Pull Request Auto Approve CI

on:
  issue_comment:
    types: [created]

jobs:
  pull-request-auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request Auto Approve
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.BOT_REVIEW_TOKEN }}
          script: |
            const commentUser = context.payload.comment.user.login;
            const commentBody = context.payload.comment.body;
            const repoOwner = context.payload.repository.owner.login;
            console.log(`Comment user: ${commentUser}`);
            console.log(`Comment body: ${commentBody}`);
            console.log(`Repo owner: ${repoOwner}`);
            if (commentUser === repoOwner || commentUser === 'Wibus' || commentUser === 'wibus-wee' ) {
              if ( commentBody.includes('/approve') ){
                github.rest.pulls.createReview({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: context.issue.number,
                  event: 'APPROVE',
                  body: `## âœ… Pull Request Auto Approved 

            Now you can merge this pull request. Thanks for your contribution.`,
                });
                github.rest.issues.createLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  name: 'ci-approved',
                });
              }
              if ( commentBody.includes('/change') ){
                github.rest.pulls.createReview({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: context.issue.number,
                  body: `## ğŸ”´ Request Changes,
                  event: 'REQUEST_CHANGES',

            Please make the requested changes and then re-request a review.`,
                });
              }
              if ( commentBody.includes('/lgtm') ){
                github.rest.pulls.createReview({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: context.issue.number,
                  event: 'APPROVE',
                  body: `## âœ… Pull Request Is Ready To Be Merged

            Now Admin can merge this pull request. Thanks for your contribution.`,
                });
                github.rest.issues.createLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  name: 'lgtm',
                });
              }
              if ( commentBody.includes('/merge') ){
                github.rest.pulls.merge({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: context.issue.number,
                  merge_method: 'squash',
                });
              }
              if ( commentBody.includes('/ci-ignore') ){
                github.rest.issues.createLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  name: 'ci-ignore',
                });
              }
              if ( commentBody.includes('/ci-no-ignore') ){
                github.rest.issues.removeLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  name: 'ci-ignore',
                });
              }
            } else {
              github.rest.issues.createComment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: context.issue.number,
                    body: `## âš ï¸ Permission denied 
                    
              Only the **owner** of the project can approve the pull request. 
                    
              åªæœ‰**é¡¹ç›®çš„æ‰€æœ‰è€…**æ‰èƒ½å‘é€å‘½ä»¤ã€‚è‹¥ä½ ç»§ç»­å‘é€æ­¤å‘½ä»¤ï¼Œä½ å°†ä¼šè¢«ç¤¾åŒºç¦è¨€ã€‚`
              })
            }

            
