name: Pull Request Auto Approve CI

on:
  issue_comment:
    types: [created]

jobs:
  pull-request-auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request Auto Approve
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.BOT_REVIEW_TOKEN }}
          script: |
            const commentUser = context.payload.comment.user.login;
            const commentBody = context.payload.comment.body;
            const repoOwner = context.payload.repository.owner.login;
            if ( commentBody.includes('/approve') ){
              if (commentUser === repoOwner || commentUser === 'Wibus' || commentUser === 'wibus-wee' ) {
                github.rest.pulls.createReview({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: context.issue.number,
                  event: 'APPROVE'
                  body: '## ✅ Pull Request Approved <br><br> This pull request has been approved by @' + commentUser + ' ',
                });
              } else {
                github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  body: `## ⚠️ Permission denied <br><br> Only the **owner** of the project can approve the pull request. <br> 只有**项目的所有者**才能发送命令自动批准拉取请求。若你继续发送此命令，你将会被社区禁言。`
                });
              }
            }
            
