name: "Organization Upstream"

on:
  schedule:
    - cron: '0 0 1/3 * *'
  push:
    branches: [ main ]

jobs:
  upstream:
    name: Upstream
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: work around permission issue
      run: git config --global --add safe.directory /__w/GS-server/GS-server
    - name: Upstream
      run: |
        sh ./scripts/upstream.sh
    - name: action-push
      uses: ludeeus/action-push@0.0.1
      env: 
        ACTION_MAIL: 62133302+wibus-wee@users.noreply.github.com
        ACTION_NAME: GitHubBot
        ACTION_BRANCH: main
        # ACTION_MESSAGE: 
